import { slugify } from "../Products/productFormState";

// Attributes use the product form's slugifier, and therefore the same one
// StoreAttribute() already uses for its codes — a code generated on this page is
// indistinguishable from one generated by the product form's inline creator.
export { slugify };

/**
 * The six types the `attributes.type` CHECK constraint accepts. Nothing else is
 * storable, so nothing else is offered.
 *
 * `hasOptions` marks the two that draw their value from a fixed list. It is the
 * single source of truth for the conditional UI: the values editor, the variant
 * toggle and the preview all key off it, and it mirrors optionTypes in
 * internal/handler/admin_attributes.go.
 */
export const ATTRIBUTE_TYPES = [
  {
    value: "select",
    label: "Single choice",
    description: "One value from a list you define",
    example: "Color → Black",
    hasOptions: true,
  },
  {
    value: "multiselect",
    label: "Multiple choice",
    description: "Several values from a list you define",
    example: "Suitable for → Indoor, Outdoor",
    hasOptions: true,
  },
  {
    value: "text",
    label: "Text",
    description: "Short free text, typed per product",
    example: "Country of origin → Portugal",
    hasOptions: false,
  },
  {
    value: "textarea",
    label: "Long text",
    description: "Multi-line free text, typed per product",
    example: "Care instructions → Machine wash cold…",
    hasOptions: false,
  },
  {
    value: "number",
    label: "Number",
    description: "A numeric value, typed per product",
    example: "Capacity → 2.5",
    hasOptions: false,
  },
  {
    value: "boolean",
    label: "Yes / No",
    description: "A simple flag, set per product",
    example: "Dishwasher safe → Yes",
    hasOptions: false,
  },
];

export function typeInfo(type) {
  return ATTRIBUTE_TYPES.find((entry) => entry.value === type) || ATTRIBUTE_TYPES[0];
}

export function hasOptions(type) {
  return typeInfo(type).hasOptions;
}

// Mirrors maxAttributeOptions in internal/handler/admin_attributes.go.
export const MAX_OPTIONS = 200;

let draftCounter = 0;

/**
 * A blank value row.
 *
 * `id` is the stored attribute_options id and stays empty for a value the
 * merchant has just added — that is exactly how the server tells "rename this
 * existing value" from "insert a new one". `key` is a client-only React key, so
 * a row keeps its identity while being typed into and reordered.
 */
export function newOption() {
  draftCounter += 1;
  return { id: "", key: `draft-${draftCounter}`, value: "", product_count: 0 };
}

export function buildInitialForm(attribute) {
  const source = attribute || {};

  return {
    name: source.name || "",
    code: source.code || "",
    type: source.type || "select",

    is_required: source.is_required != null ? source.is_required : false,
    is_variant: source.is_variant != null ? source.is_variant : false,
    sort_order: source.sort_order != null ? String(source.sort_order) : "0",
  };
}

export function buildInitialOptions(options) {
  if (!Array.isArray(options) || options.length === 0) return [newOption()];

  return options.map((option) => ({
    id: option.id || "",
    key: option.id || `stored-${option.value}`,
    value: option.value || "",
    product_count: option.product_count ?? 0,
  }));
}

export function toPayload(form, options, redirectTo) {
  return {
    name: form.name,
    code: form.code || slugify(form.name),
    type: form.type,

    is_required: form.is_required,
    // A variant axis is built from a fixed list of values, so is_variant is only
    // meaningful for the option types. Forcing it false elsewhere keeps the
    // stored flag honest even if the merchant switched type after setting it.
    is_variant: hasOptions(form.type) ? form.is_variant : false,
    sort_order: form.sort_order || "0",

    // Array order is the stored sort_order. Blank rows are dropped rather than
    // rejected, so a half-typed row the merchant abandoned is not an error.
    options: hasOptions(form.type)
      ? options
          .filter((option) => option.value.trim())
          .map((option) => ({ id: option.id, value: option.value.trim() }))
      : [],

    redirect_to: redirectTo,
  };
}

/**
 * Mirrors validateAttributeForm in internal/handler/admin_attributes.go so the
 * merchant sees problems before a round trip. The server stays authoritative:
 * name and code uniqueness, and whether a type change is still allowed, can only
 * be settled there.
 *
 * @param {object} form
 * @param {Array} options
 * @param {object} [context] `{ isEdit, originalType, productCount }`
 */
export function validateForm(form, options = [], context = {}) {
  const errors = {};

  const name = form.name.trim();
  if (!name) errors.name = "Attribute name is required.";
  else if (name.length > 255) errors.name = "Attribute name must be 255 characters or fewer.";

  const code = form.code.trim() ? slugify(form.code) : slugify(name);
  if (name && !code) {
    errors.code = "Enter a code — one could not be generated from the attribute name.";
  } else if (code.length > 100) {
    errors.code = "Code must be 100 characters or fewer.";
  }

  if (!ATTRIBUTE_TYPES.some((entry) => entry.value === form.type)) {
    errors.type = "Choose a valid attribute type.";
  } else if (
    context.isEdit &&
    context.originalType &&
    form.type !== context.originalType &&
    (context.productCount ?? 0) > 0
  ) {
    const count = context.productCount;
    errors.type = `This attribute is used by ${count} product${count === 1 ? "" : "s"}, so its type can no longer change. Create a new attribute instead.`;
  }

  const sortOrder = String(form.sort_order ?? "").trim();
  if (sortOrder) {
    if (!/^-?\d+$/.test(sortOrder)) errors.sort_order = "Enter a whole number.";
    else if (Number(sortOrder) < 0) errors.sort_order = "Value cannot be negative.";
  }

  if (hasOptions(form.type)) {
    const filled = options.map((option) => option.value.trim()).filter(Boolean);

    if (filled.length === 0) {
      errors.options = "Add at least one value, or choose a type that does not use a fixed list.";
    } else if (filled.length > MAX_OPTIONS) {
      errors.options = `An attribute can have at most ${MAX_OPTIONS} values.`;
    } else if (filled.some((value) => value.length > 255)) {
      errors.options = "Each value must be 255 characters or fewer.";
    } else {
      // attribute_options is UNIQUE (attribute_id, value); the comparison is
      // case-insensitive so "Red" and "red" are reported as the clash they are.
      const seen = new Set();
      const duplicate = filled.find((value) => {
        const key = value.toLowerCase();
        if (seen.has(key)) return true;
        seen.add(key);
        return false;
      });
      if (duplicate) {
        errors.options = `"${duplicate}" appears more than once. Each value must be unique.`;
      }
    }
  }

  return errors;
}
