// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: addresses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAddressesByUser = `-- name: CountAddressesByUser :one
SELECT COUNT(*) FROM addresses WHERE user_id = $1
`

func (q *Queries) CountAddressesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, label, first_name, last_name, company, address_line1, address_line2, city, state, postal_code, country, phone, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, label, first_name, last_name, company, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	Label        string      `db:"label" json:"label"`
	FirstName    string      `db:"first_name" json:"first_name"`
	LastName     string      `db:"last_name" json:"last_name"`
	Company      pgtype.Text `db:"company" json:"company"`
	AddressLine1 string      `db:"address_line1" json:"address_line1"`
	AddressLine2 pgtype.Text `db:"address_line2" json:"address_line2"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Country      string      `db:"country" json:"country"`
	Phone        pgtype.Text `db:"phone" json:"phone"`
	IsDefault    bool        `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, label, first_name, last_name, company, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at FROM addresses WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id pgtype.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultAddress = `-- name: GetDefaultAddress :one
SELECT id, user_id, label, first_name, last_name, company, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at FROM addresses
WHERE user_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultAddress(ctx context.Context, userID pgtype.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getDefaultAddress, userID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, label, first_name, last_name, company, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at FROM addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID pgtype.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE addresses SET is_default = false WHERE user_id = $1
`

func (q *Queries) SetDefaultAddress(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, userID)
	return err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET label = $2, first_name = $3, last_name = $4, company = $5, address_line1 = $6, address_line2 = $7, city = $8, state = $9, postal_code = $10, country = $11, phone = $12, is_default = $13
WHERE id = $1
RETURNING id, user_id, label, first_name, last_name, company, address_line1, address_line2, city, state, postal_code, country, phone, is_default, created_at, updated_at
`

type UpdateAddressParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Label        string      `db:"label" json:"label"`
	FirstName    string      `db:"first_name" json:"first_name"`
	LastName     string      `db:"last_name" json:"last_name"`
	Company      pgtype.Text `db:"company" json:"company"`
	AddressLine1 string      `db:"address_line1" json:"address_line1"`
	AddressLine2 pgtype.Text `db:"address_line2" json:"address_line2"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Country      string      `db:"country" json:"country"`
	Phone        pgtype.Text `db:"phone" json:"phone"`
	IsDefault    bool        `db:"is_default" json:"is_default"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.FirstName,
		arg.LastName,
		arg.Company,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
