// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: attributes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (code, name, type, is_required, is_variant, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at
`

type CreateAttributeParams struct {
	Code       string `db:"code" json:"code"`
	Name       string `db:"name" json:"name"`
	Type       string `db:"type" json:"type"`
	IsRequired bool   `db:"is_required" json:"is_required"`
	IsVariant  bool   `db:"is_variant" json:"is_variant"`
	SortOrder  int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.IsRequired,
		arg.IsVariant,
		arg.SortOrder,
	)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttributeOption = `-- name: CreateAttributeOption :one
INSERT INTO attribute_options (attribute_id, value, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (attribute_id, value) DO UPDATE SET value = EXCLUDED.value
RETURNING id, attribute_id, value, sort_order, created_at
`

type CreateAttributeOptionParams struct {
	AttributeID pgtype.UUID `db:"attribute_id" json:"attribute_id"`
	Value       string      `db:"value" json:"value"`
	SortOrder   int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateAttributeOption(ctx context.Context, arg CreateAttributeOptionParams) (AttributeOption, error) {
	row := q.db.QueryRow(ctx, createAttributeOption, arg.AttributeID, arg.Value, arg.SortOrder)
	var i AttributeOption
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createProductAttribute = `-- name: CreateProductAttribute :one
INSERT INTO product_attributes (product_id, attribute_id, option_id, value, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, attribute_id, option_id, value, sort_order, created_at
`

type CreateProductAttributeParams struct {
	ProductID   pgtype.UUID `db:"product_id" json:"product_id"`
	AttributeID pgtype.UUID `db:"attribute_id" json:"attribute_id"`
	OptionID    pgtype.UUID `db:"option_id" json:"option_id"`
	Value       pgtype.Text `db:"value" json:"value"`
	SortOrder   int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRow(ctx, createProductAttribute,
		arg.ProductID,
		arg.AttributeID,
		arg.OptionID,
		arg.Value,
		arg.SortOrder,
	)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AttributeID,
		&i.OptionID,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductAttributesByProductID = `-- name: DeleteProductAttributesByProductID :exec
DELETE FROM product_attributes WHERE product_id = $1
`

func (q *Queries) DeleteProductAttributesByProductID(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductAttributesByProductID, productID)
	return err
}

const getAttributeByCode = `-- name: GetAttributeByCode :one
SELECT id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at FROM attributes WHERE code = $1
`

func (q *Queries) GetAttributeByCode(ctx context.Context, code string) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByCode, code)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttributeByID = `-- name: GetAttributeByID :one
SELECT id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at FROM attributes WHERE id = $1
`

func (q *Queries) GetAttributeByID(ctx context.Context, id pgtype.UUID) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByID, id)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttributeOptions = `-- name: ListAttributeOptions :many
SELECT id, attribute_id, value, sort_order, created_at FROM attribute_options
ORDER BY sort_order ASC, value ASC
`

func (q *Queries) ListAttributeOptions(ctx context.Context) ([]AttributeOption, error) {
	rows, err := q.db.Query(ctx, listAttributeOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeOption{}
	for rows.Next() {
		var i AttributeOption
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributes = `-- name: ListAttributes :many
SELECT id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at FROM attributes
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListAttributes(ctx context.Context) ([]Attribute, error) {
	rows, err := q.db.Query(ctx, listAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.IsRequired,
			&i.IsVariant,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByAttribute = `-- name: ListOptionsByAttribute :many
SELECT id, attribute_id, value, sort_order, created_at FROM attribute_options
WHERE attribute_id = $1
ORDER BY sort_order ASC, value ASC
`

func (q *Queries) ListOptionsByAttribute(ctx context.Context, attributeID pgtype.UUID) ([]AttributeOption, error) {
	rows, err := q.db.Query(ctx, listOptionsByAttribute, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeOption{}
	for rows.Next() {
		var i AttributeOption
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributes = `-- name: ListProductAttributes :many
SELECT pa.id, pa.product_id, pa.attribute_id, pa.option_id, pa.value, pa.sort_order, pa.created_at, a.code AS attribute_code, a.name AS attribute_name, a.type AS attribute_type, o.value AS option_value
FROM product_attributes pa
JOIN attributes a ON a.id = pa.attribute_id
LEFT JOIN attribute_options o ON o.id = pa.option_id
WHERE pa.product_id = $1
ORDER BY pa.sort_order ASC, a.name ASC
`

type ListProductAttributesRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ProductID     pgtype.UUID        `db:"product_id" json:"product_id"`
	AttributeID   pgtype.UUID        `db:"attribute_id" json:"attribute_id"`
	OptionID      pgtype.UUID        `db:"option_id" json:"option_id"`
	Value         pgtype.Text        `db:"value" json:"value"`
	SortOrder     int32              `db:"sort_order" json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AttributeCode string             `db:"attribute_code" json:"attribute_code"`
	AttributeName string             `db:"attribute_name" json:"attribute_name"`
	AttributeType string             `db:"attribute_type" json:"attribute_type"`
	OptionValue   pgtype.Text        `db:"option_value" json:"option_value"`
}

func (q *Queries) ListProductAttributes(ctx context.Context, productID pgtype.UUID) ([]ListProductAttributesRow, error) {
	rows, err := q.db.Query(ctx, listProductAttributes, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductAttributesRow{}
	for rows.Next() {
		var i ListProductAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AttributeID,
			&i.OptionID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
			&i.AttributeCode,
			&i.AttributeName,
			&i.AttributeType,
			&i.OptionValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
