// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: attributes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttributesWithCode = `-- name: CountAttributesWithCode :one
SELECT COUNT(*) FROM attributes
WHERE code = $1
  AND ($2::uuid IS NULL OR id <> $2::uuid)
`

type CountAttributesWithCodeParams struct {
	Code      string      `db:"code" json:"code"`
	ExcludeID pgtype.UUID `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) CountAttributesWithCode(ctx context.Context, arg CountAttributesWithCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttributesWithCode, arg.Code, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttributesWithName = `-- name: CountAttributesWithName :one
SELECT COUNT(*) FROM attributes
WHERE lower(name) = lower($1::text)
  AND ($2::uuid IS NULL OR id <> $2::uuid)
`

type CountAttributesWithNameParams struct {
	Name      string      `db:"name" json:"name"`
	ExcludeID pgtype.UUID `db:"exclude_id" json:"exclude_id"`
}

func (q *Queries) CountAttributesWithName(ctx context.Context, arg CountAttributesWithNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttributesWithName, arg.Name, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsUsingAttribute = `-- name: CountProductsUsingAttribute :one
SELECT COUNT(DISTINCT product_id) FROM product_attributes WHERE attribute_id = $1
`

func (q *Queries) CountProductsUsingAttribute(ctx context.Context, attributeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsUsingAttribute, attributeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsUsingOption = `-- name: CountProductsUsingOption :one
SELECT COUNT(DISTINCT product_id) FROM product_attributes WHERE option_id = $1
`

func (q *Queries) CountProductsUsingOption(ctx context.Context, optionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsUsingOption, optionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (code, name, type, is_required, is_variant, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at
`

type CreateAttributeParams struct {
	Code       string `db:"code" json:"code"`
	Name       string `db:"name" json:"name"`
	Type       string `db:"type" json:"type"`
	IsRequired bool   `db:"is_required" json:"is_required"`
	IsVariant  bool   `db:"is_variant" json:"is_variant"`
	SortOrder  int32  `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.IsRequired,
		arg.IsVariant,
		arg.SortOrder,
	)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttributeOption = `-- name: CreateAttributeOption :one
INSERT INTO attribute_options (attribute_id, value, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (attribute_id, value) DO UPDATE SET value = EXCLUDED.value
RETURNING id, attribute_id, value, sort_order, created_at
`

type CreateAttributeOptionParams struct {
	AttributeID pgtype.UUID `db:"attribute_id" json:"attribute_id"`
	Value       string      `db:"value" json:"value"`
	SortOrder   int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateAttributeOption(ctx context.Context, arg CreateAttributeOptionParams) (AttributeOption, error) {
	row := q.db.QueryRow(ctx, createAttributeOption, arg.AttributeID, arg.Value, arg.SortOrder)
	var i AttributeOption
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createProductAttribute = `-- name: CreateProductAttribute :one
INSERT INTO product_attributes (product_id, attribute_id, option_id, value, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, attribute_id, option_id, value, sort_order, created_at
`

type CreateProductAttributeParams struct {
	ProductID   pgtype.UUID `db:"product_id" json:"product_id"`
	AttributeID pgtype.UUID `db:"attribute_id" json:"attribute_id"`
	OptionID    pgtype.UUID `db:"option_id" json:"option_id"`
	Value       pgtype.Text `db:"value" json:"value"`
	SortOrder   int32       `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRow(ctx, createProductAttribute,
		arg.ProductID,
		arg.AttributeID,
		arg.OptionID,
		arg.Value,
		arg.SortOrder,
	)
	var i ProductAttribute
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.AttributeID,
		&i.OptionID,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttribute = `-- name: DeleteAttribute :exec
DELETE FROM attributes WHERE id = $1
`

// product_attributes.attribute_id is ON DELETE CASCADE, so this would take the
// product data with it. The handler refuses while the attribute is in use.
func (q *Queries) DeleteAttribute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttribute, id)
	return err
}

const deleteAttributeOption = `-- name: DeleteAttributeOption :exec
DELETE FROM attribute_options WHERE id = $1
`

func (q *Queries) DeleteAttributeOption(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttributeOption, id)
	return err
}

const deleteProductAttributesByProductID = `-- name: DeleteProductAttributesByProductID :exec
DELETE FROM product_attributes WHERE product_id = $1
`

func (q *Queries) DeleteProductAttributesByProductID(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductAttributesByProductID, productID)
	return err
}

const getAttributeByCode = `-- name: GetAttributeByCode :one
SELECT id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at FROM attributes WHERE code = $1
`

func (q *Queries) GetAttributeByCode(ctx context.Context, code string) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByCode, code)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttributeByID = `-- name: GetAttributeByID :one
SELECT id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at FROM attributes WHERE id = $1
`

func (q *Queries) GetAttributeByID(ctx context.Context, id pgtype.UUID) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByID, id)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAttributeOption = `-- name: InsertAttributeOption :one
INSERT INTO attribute_options (attribute_id, value, sort_order)
VALUES ($1, $2, $3)
RETURNING id, attribute_id, value, sort_order, created_at
`

type InsertAttributeOptionParams struct {
	AttributeID pgtype.UUID `db:"attribute_id" json:"attribute_id"`
	Value       string      `db:"value" json:"value"`
	SortOrder   int32       `db:"sort_order" json:"sort_order"`
}

// Distinct from CreateAttributeOption above, which the product form's JSON
// endpoint still uses and which does not carry a caller-chosen sort order.
func (q *Queries) InsertAttributeOption(ctx context.Context, arg InsertAttributeOptionParams) (AttributeOption, error) {
	row := q.db.QueryRow(ctx, insertAttributeOption, arg.AttributeID, arg.Value, arg.SortOrder)
	var i AttributeOption
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listAttributeOptions = `-- name: ListAttributeOptions :many
SELECT id, attribute_id, value, sort_order, created_at FROM attribute_options
ORDER BY sort_order ASC, value ASC
`

func (q *Queries) ListAttributeOptions(ctx context.Context) ([]AttributeOption, error) {
	rows, err := q.db.Query(ctx, listAttributeOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeOption{}
	for rows.Next() {
		var i AttributeOption
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributes = `-- name: ListAttributes :many
SELECT id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at FROM attributes
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListAttributes(ctx context.Context) ([]Attribute, error) {
	rows, err := q.db.Query(ctx, listAttributes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.IsRequired,
			&i.IsVariant,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributesWithUsage = `-- name: ListAttributesWithUsage :many

SELECT a.id, a.code, a.name, a.type, a.is_required, a.is_variant, a.sort_order, a.created_at, a.updated_at,
       (SELECT COUNT(*) FROM attribute_options o WHERE o.attribute_id = a.id)::bigint AS option_count,
       (SELECT COUNT(DISTINCT pa.product_id) FROM product_attributes pa WHERE pa.attribute_id = a.id)::bigint AS product_count
FROM attributes a
ORDER BY a.sort_order ASC, a.name ASC
`

type ListAttributesWithUsageRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	Type         string             `db:"type" json:"type"`
	IsRequired   bool               `db:"is_required" json:"is_required"`
	IsVariant    bool               `db:"is_variant" json:"is_variant"`
	SortOrder    int32              `db:"sort_order" json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OptionCount  int64              `db:"option_count" json:"option_count"`
	ProductCount int64              `db:"product_count" json:"product_count"`
}

// ---------------------------------------------------------------------------
// Admin attribute management
//
// Everything below backs the admin Attributes screens. The queries above are
// older and still serve the product form's inline creator; they are left alone.
// ---------------------------------------------------------------------------
// Admin index. Both counts are derived rather than stored, so neither can drift:
// `option_count` is how many values the attribute offers, `product_count` how
// many distinct products currently carry it.
func (q *Queries) ListAttributesWithUsage(ctx context.Context) ([]ListAttributesWithUsageRow, error) {
	rows, err := q.db.Query(ctx, listAttributesWithUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttributesWithUsageRow{}
	for rows.Next() {
		var i ListAttributesWithUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.IsRequired,
			&i.IsVariant,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OptionCount,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionUsage = `-- name: ListOptionUsage :many

SELECT o.id AS option_id,
       COUNT(DISTINCT pa.product_id)::bigint AS product_count
FROM attribute_options o
LEFT JOIN product_attributes pa ON pa.option_id = o.id
WHERE o.attribute_id = $1
GROUP BY o.id
`

type ListOptionUsageRow struct {
	OptionID     pgtype.UUID `db:"option_id" json:"option_id"`
	ProductCount int64       `db:"product_count" json:"product_count"`
}

// ---------------------------------------------------------------------------
// Values
//
// Values are diffed by id, never cleared and re-inserted:
// product_attributes.option_id is ON DELETE SET NULL, so dropping and recreating
// an option would silently blank the value on every product that carries it.
// ---------------------------------------------------------------------------
// Per-value product counts, so the form can warn before removing a value that
// products already reference.
func (q *Queries) ListOptionUsage(ctx context.Context, attributeID pgtype.UUID) ([]ListOptionUsageRow, error) {
	rows, err := q.db.Query(ctx, listOptionUsage, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionUsageRow{}
	for rows.Next() {
		var i ListOptionUsageRow
		if err := rows.Scan(&i.OptionID, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByAttribute = `-- name: ListOptionsByAttribute :many
SELECT id, attribute_id, value, sort_order, created_at FROM attribute_options
WHERE attribute_id = $1
ORDER BY sort_order ASC, value ASC
`

func (q *Queries) ListOptionsByAttribute(ctx context.Context, attributeID pgtype.UUID) ([]AttributeOption, error) {
	rows, err := q.db.Query(ctx, listOptionsByAttribute, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeOption{}
	for rows.Next() {
		var i AttributeOption
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductAttributes = `-- name: ListProductAttributes :many
SELECT pa.id, pa.product_id, pa.attribute_id, pa.option_id, pa.value, pa.sort_order, pa.created_at, a.code AS attribute_code, a.name AS attribute_name, a.type AS attribute_type, o.value AS option_value
FROM product_attributes pa
JOIN attributes a ON a.id = pa.attribute_id
LEFT JOIN attribute_options o ON o.id = pa.option_id
WHERE pa.product_id = $1
ORDER BY pa.sort_order ASC, a.name ASC
`

type ListProductAttributesRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ProductID     pgtype.UUID        `db:"product_id" json:"product_id"`
	AttributeID   pgtype.UUID        `db:"attribute_id" json:"attribute_id"`
	OptionID      pgtype.UUID        `db:"option_id" json:"option_id"`
	Value         pgtype.Text        `db:"value" json:"value"`
	SortOrder     int32              `db:"sort_order" json:"sort_order"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AttributeCode string             `db:"attribute_code" json:"attribute_code"`
	AttributeName string             `db:"attribute_name" json:"attribute_name"`
	AttributeType string             `db:"attribute_type" json:"attribute_type"`
	OptionValue   pgtype.Text        `db:"option_value" json:"option_value"`
}

func (q *Queries) ListProductAttributes(ctx context.Context, productID pgtype.UUID) ([]ListProductAttributesRow, error) {
	rows, err := q.db.Query(ctx, listProductAttributes, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductAttributesRow{}
	for rows.Next() {
		var i ListProductAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AttributeID,
			&i.OptionID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
			&i.AttributeCode,
			&i.AttributeName,
			&i.AttributeType,
			&i.OptionValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttribute = `-- name: UpdateAttribute :one
UPDATE attributes
SET code = $2, name = $3, is_required = $4, is_variant = $5, sort_order = $6
WHERE id = $1
RETURNING id, code, name, type, is_required, is_variant, sort_order, created_at, updated_at
`

type UpdateAttributeParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	Code       string      `db:"code" json:"code"`
	Name       string      `db:"name" json:"name"`
	IsRequired bool        `db:"is_required" json:"is_required"`
	IsVariant  bool        `db:"is_variant" json:"is_variant"`
	SortOrder  int32       `db:"sort_order" json:"sort_order"`
}

// `type` is deliberately absent. A stored product_attributes row was written to
// suit the attribute's type (option_id for select/multiselect, value for the
// rest), so changing type on an attribute in use would silently invalidate it.
// The handler allows a type change only while product_count is 0, and does it
// through UpdateAttributeType below.
func (q *Queries) UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, updateAttribute,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.IsRequired,
		arg.IsVariant,
		arg.SortOrder,
	)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.IsRequired,
		&i.IsVariant,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAttributeOption = `-- name: UpdateAttributeOption :exec
UPDATE attribute_options SET value = $2, sort_order = $3 WHERE id = $1
`

type UpdateAttributeOptionParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Value     string      `db:"value" json:"value"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
}

// Renaming a value in place keeps every product_attributes.option_id pointing at
// it, so relabelling "Navy" to "Navy Blue" never touches product data.
func (q *Queries) UpdateAttributeOption(ctx context.Context, arg UpdateAttributeOptionParams) error {
	_, err := q.db.Exec(ctx, updateAttributeOption, arg.ID, arg.Value, arg.SortOrder)
	return err
}

const updateAttributeType = `-- name: UpdateAttributeType :exec
UPDATE attributes SET type = $2 WHERE id = $1
`

type UpdateAttributeTypeParams struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Type string      `db:"type" json:"type"`
}

// Only ever called for an attribute no product references yet.
func (q *Queries) UpdateAttributeType(ctx context.Context, arg UpdateAttributeTypeParams) error {
	_, err := q.db.Exec(ctx, updateAttributeType, arg.ID, arg.Type)
	return err
}
