// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductToCollection = `-- name: AddProductToCollection :exec
INSERT INTO collection_products (collection_id, product_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (collection_id, product_id) DO UPDATE SET position = EXCLUDED.position
`

type AddProductToCollectionParams struct {
	CollectionID pgtype.UUID `db:"collection_id" json:"collection_id"`
	ProductID    pgtype.UUID `db:"product_id" json:"product_id"`
	Position     int32       `db:"position" json:"position"`
}

// Idempotent: re-adding a product already in the collection just re-seats it
// rather than failing on the primary key.
func (q *Queries) AddProductToCollection(ctx context.Context, arg AddProductToCollectionParams) error {
	_, err := q.db.Exec(ctx, addProductToCollection, arg.CollectionID, arg.ProductID, arg.Position)
	return err
}

const clearCollectionProducts = `-- name: ClearCollectionProducts :exec
DELETE FROM collection_products WHERE collection_id = $1
`

func (q *Queries) ClearCollectionProducts(ctx context.Context, collectionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCollectionProducts, collectionID)
	return err
}

const countActiveCollectionProducts = `-- name: CountActiveCollectionProducts :one
SELECT COUNT(*)
FROM collection_products cp
JOIN products p ON p.id = cp.product_id
WHERE cp.collection_id = $1 AND p.is_active = true
`

func (q *Queries) CountActiveCollectionProducts(ctx context.Context, collectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCollectionProducts, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveCollections = `-- name: CountActiveCollections :one
SELECT COUNT(*) FROM collections WHERE is_active = true
`

func (q *Queries) CountActiveCollections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCollections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCollectionsWithName = `-- name: CountCollectionsWithName :one
SELECT COUNT(*) FROM collections
WHERE lower(name) = lower($1::text)
  AND ($2::uuid IS NULL OR id <> $2::uuid)
`

type CountCollectionsWithNameParams struct {
	Name      string      `db:"name" json:"name"`
	ExcludeID pgtype.UUID `db:"exclude_id" json:"exclude_id"`
}

// Collections have no parent, so a name is compared against every other
// collection. Case-insensitive, like the category sibling check.
func (q *Queries) CountCollectionsWithName(ctx context.Context, arg CountCollectionsWithNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectionsWithName, arg.Name, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCollectionsWithSlug = `-- name: CountCollectionsWithSlug :one
SELECT COUNT(*) FROM collections
WHERE slug = $1
  AND ($2::uuid IS NULL OR id <> $2::uuid)
`

type CountCollectionsWithSlugParams struct {
	Slug      string      `db:"slug" json:"slug"`
	ExcludeID pgtype.UUID `db:"exclude_id" json:"exclude_id"`
}

// Uniqueness check for the admin form. sqlc.narg('exclude_id') is the
// collection being edited, so saving it unchanged is not a conflict.
func (q *Queries) CountCollectionsWithSlug(ctx context.Context, arg CountCollectionsWithSlugParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectionsWithSlug, arg.Slug, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsForPicker = `-- name: CountProductsForPicker :one
SELECT COUNT(*)
FROM products p
WHERE ($1::text IS NULL
       OR p.name ILIKE '%' || $1::text || '%'
       OR p.sku ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountProductsForPicker(ctx context.Context, keyword pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsForPicker, keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsInCollection = `-- name: CountProductsInCollection :one
SELECT COUNT(*) FROM collection_products WHERE collection_id = $1
`

func (q *Queries) CountProductsInCollection(ctx context.Context, collectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsInCollection, collectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValidProductIDs = `-- name: CountValidProductIDs :one
SELECT COUNT(*) FROM products WHERE id = ANY($1::uuid[])
`

// How many of the posted product ids actually exist. The form refuses to save
// a membership list containing a product that has since been deleted.
func (q *Queries) CountValidProductIDs(ctx context.Context, ids []pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countValidProductIDs, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (
    name, slug, description, image_url,
    is_active, is_featured, sort_order,
    meta_title, meta_description, meta_keywords
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, slug, description, image_url, is_active, is_featured, sort_order, meta_title, meta_description, meta_keywords, created_at, updated_at
`

type CreateCollectionParams struct {
	Name            string      `db:"name" json:"name"`
	Slug            string      `db:"slug" json:"slug"`
	Description     pgtype.Text `db:"description" json:"description"`
	ImageUrl        pgtype.Text `db:"image_url" json:"image_url"`
	IsActive        bool        `db:"is_active" json:"is_active"`
	IsFeatured      bool        `db:"is_featured" json:"is_featured"`
	SortOrder       int32       `db:"sort_order" json:"sort_order"`
	MetaTitle       pgtype.Text `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text `db:"meta_description" json:"meta_description"`
	MetaKeywords    pgtype.Text `db:"meta_keywords" json:"meta_keywords"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.IsActive,
		arg.IsFeatured,
		arg.SortOrder,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

// collection_products is ON DELETE CASCADE, so membership goes with it. The
// products themselves are untouched.
func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, slug, description, image_url, is_active, is_featured, sort_order, meta_title, meta_description, meta_keywords, created_at, updated_at FROM collections WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT id, name, slug, description, image_url, is_active, is_featured, sort_order, meta_title, meta_description, meta_keywords, created_at, updated_at FROM collections WHERE slug = $1
`

func (q *Queries) GetCollectionBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCollectionProducts = `-- name: ListActiveCollectionProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, p.short_description, p.brand, p.tags, p.cost_price, p.track_inventory, p.allow_backorders, p.low_stock_threshold, p.length, p.width, p.height, p.meta_keywords, p.sort_order, c.name AS category_name, c.slug AS category_slug
FROM collection_products cp
JOIN products p ON p.id = cp.product_id
JOIN categories c ON c.id = p.category_id
WHERE cp.collection_id = $1 AND p.is_active = true
ORDER BY cp.position ASC, p.name ASC
LIMIT $2 OFFSET $3
`

type ListActiveCollectionProductsParams struct {
	CollectionID pgtype.UUID `db:"collection_id" json:"collection_id"`
	Limit        int32       `db:"limit" json:"limit"`
	Offset       int32       `db:"offset" json:"offset"`
}

type ListActiveCollectionProductsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	Name              string             `db:"name" json:"name"`
	Slug              string             `db:"slug" json:"slug"`
	Description       pgtype.Text        `db:"description" json:"description"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice    pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku               pgtype.Text        `db:"sku" json:"sku"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	IsFeatured        bool               `db:"is_featured" json:"is_featured"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight            pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle         pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription   pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ShortDescription  pgtype.Text        `db:"short_description" json:"short_description"`
	Brand             pgtype.Text        `db:"brand" json:"brand"`
	Tags              []string           `db:"tags" json:"tags"`
	CostPrice         pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	TrackInventory    bool               `db:"track_inventory" json:"track_inventory"`
	AllowBackorders   bool               `db:"allow_backorders" json:"allow_backorders"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	Length            pgtype.Numeric     `db:"length" json:"length"`
	Width             pgtype.Numeric     `db:"width" json:"width"`
	Height            pgtype.Numeric     `db:"height" json:"height"`
	MetaKeywords      pgtype.Text        `db:"meta_keywords" json:"meta_keywords"`
	SortOrder         int32              `db:"sort_order" json:"sort_order"`
	CategoryName      string             `db:"category_name" json:"category_name"`
	CategorySlug      string             `db:"category_slug" json:"category_slug"`
}

// /collections/{slug}. Curated order is the storefront order; inactive
// products drop out.
func (q *Queries) ListActiveCollectionProducts(ctx context.Context, arg ListActiveCollectionProductsParams) ([]ListActiveCollectionProductsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCollectionProducts, arg.CollectionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCollectionProductsRow{}
	for rows.Next() {
		var i ListActiveCollectionProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortDescription,
			&i.Brand,
			&i.Tags,
			&i.CostPrice,
			&i.TrackInventory,
			&i.AllowBackorders,
			&i.LowStockThreshold,
			&i.Length,
			&i.Width,
			&i.Height,
			&i.MetaKeywords,
			&i.SortOrder,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCollections = `-- name: ListActiveCollections :many

SELECT c.id, c.name, c.slug, c.description, c.image_url, c.is_active, c.is_featured, c.sort_order, c.meta_title, c.meta_description, c.meta_keywords, c.created_at, c.updated_at, COUNT(cp.product_id)::bigint AS product_count
FROM collections c
LEFT JOIN collection_products cp ON cp.collection_id = c.id
LEFT JOIN products p ON p.id = cp.product_id AND p.is_active = true
WHERE c.is_active = true
GROUP BY c.id
ORDER BY c.sort_order ASC, c.name ASC
`

type ListActiveCollectionsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	SortOrder       int32              `db:"sort_order" json:"sort_order"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	MetaKeywords    pgtype.Text        `db:"meta_keywords" json:"meta_keywords"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductCount    int64              `db:"product_count" json:"product_count"`
}

// ---------------------------------------------------------------------------
// Storefront
// ---------------------------------------------------------------------------
// /collections. Only counts products a shopper can actually buy into.
func (q *Queries) ListActiveCollections(ctx context.Context) ([]ListActiveCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCollectionsRow{}
	for rows.Next() {
		var i ListActiveCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.SortOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionProducts = `-- name: ListCollectionProducts :many

SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, p.short_description, p.brand, p.tags, p.cost_price, p.track_inventory, p.allow_backorders, p.low_stock_threshold, p.length, p.width, p.height, p.meta_keywords, p.sort_order, cp.position, c.name AS category_name, c.slug AS category_slug
FROM collection_products cp
JOIN products p ON p.id = cp.product_id
JOIN categories c ON c.id = p.category_id
WHERE cp.collection_id = $1
ORDER BY cp.position ASC, p.name ASC
`

type ListCollectionProductsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	Name              string             `db:"name" json:"name"`
	Slug              string             `db:"slug" json:"slug"`
	Description       pgtype.Text        `db:"description" json:"description"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice    pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku               pgtype.Text        `db:"sku" json:"sku"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	IsFeatured        bool               `db:"is_featured" json:"is_featured"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight            pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle         pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription   pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ShortDescription  pgtype.Text        `db:"short_description" json:"short_description"`
	Brand             pgtype.Text        `db:"brand" json:"brand"`
	Tags              []string           `db:"tags" json:"tags"`
	CostPrice         pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	TrackInventory    bool               `db:"track_inventory" json:"track_inventory"`
	AllowBackorders   bool               `db:"allow_backorders" json:"allow_backorders"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	Length            pgtype.Numeric     `db:"length" json:"length"`
	Width             pgtype.Numeric     `db:"width" json:"width"`
	Height            pgtype.Numeric     `db:"height" json:"height"`
	MetaKeywords      pgtype.Text        `db:"meta_keywords" json:"meta_keywords"`
	SortOrder         int32              `db:"sort_order" json:"sort_order"`
	Position          int32              `db:"position" json:"position"`
	CategoryName      string             `db:"category_name" json:"category_name"`
	CategorySlug      string             `db:"category_slug" json:"category_slug"`
}

// ---------------------------------------------------------------------------
// Membership
// ---------------------------------------------------------------------------
// The admin editor's list: every member in curated order, including products
// that are currently inactive so the merchant can see and fix them.
func (q *Queries) ListCollectionProducts(ctx context.Context, collectionID pgtype.UUID) ([]ListCollectionProductsRow, error) {
	rows, err := q.db.Query(ctx, listCollectionProducts, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionProductsRow{}
	for rows.Next() {
		var i ListCollectionProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortDescription,
			&i.Brand,
			&i.Tags,
			&i.CostPrice,
			&i.TrackInventory,
			&i.AllowBackorders,
			&i.LowStockThreshold,
			&i.Length,
			&i.Width,
			&i.Height,
			&i.MetaKeywords,
			&i.SortOrder,
			&i.Position,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.name, c.slug, c.description, c.image_url, c.is_active, c.is_featured, c.sort_order, c.meta_title, c.meta_description, c.meta_keywords, c.created_at, c.updated_at, COUNT(cp.product_id)::bigint AS product_count
FROM collections c
LEFT JOIN collection_products cp ON cp.collection_id = c.id
GROUP BY c.id
ORDER BY c.sort_order ASC, c.name ASC
`

type ListCollectionsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	SortOrder       int32              `db:"sort_order" json:"sort_order"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	MetaKeywords    pgtype.Text        `db:"meta_keywords" json:"meta_keywords"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductCount    int64              `db:"product_count" json:"product_count"`
}

// Admin index. product_count comes from the join table rather than a stored
// counter so it cannot drift.
func (q *Queries) ListCollections(ctx context.Context) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsRow{}
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.SortOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedCollections = `-- name: ListFeaturedCollections :many
SELECT c.id, c.name, c.slug, c.description, c.image_url, c.is_active, c.is_featured, c.sort_order, c.meta_title, c.meta_description, c.meta_keywords, c.created_at, c.updated_at, COUNT(cp.product_id)::bigint AS product_count
FROM collections c
LEFT JOIN collection_products cp ON cp.collection_id = c.id
WHERE c.is_active = true AND c.is_featured = true
GROUP BY c.id
ORDER BY c.sort_order ASC, c.name ASC
`

type ListFeaturedCollectionsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	SortOrder       int32              `db:"sort_order" json:"sort_order"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	MetaKeywords    pgtype.Text        `db:"meta_keywords" json:"meta_keywords"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductCount    int64              `db:"product_count" json:"product_count"`
}

func (q *Queries) ListFeaturedCollections(ctx context.Context) ([]ListFeaturedCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedCollectionsRow{}
	for rows.Next() {
		var i ListFeaturedCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.SortOrder,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.MetaKeywords,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByIDs = `-- name: ListProductsByIDs :many
SELECT p.id, p.name, p.slug, p.sku, p.price, p.image_url, p.is_active,
       p.stock_quantity, c.name AS category_name
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.id = ANY($1::uuid[])
`

type ListProductsByIDsRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	Name          string         `db:"name" json:"name"`
	Slug          string         `db:"slug" json:"slug"`
	Sku           pgtype.Text    `db:"sku" json:"sku"`
	Price         pgtype.Numeric `db:"price" json:"price"`
	ImageUrl      pgtype.Text    `db:"image_url" json:"image_url"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	StockQuantity int32          `db:"stock_quantity" json:"stock_quantity"`
	CategoryName  string         `db:"category_name" json:"category_name"`
}

// Rehydrates a staged selection (create form) or a posted list after a
// validation bounce, without a query per product.
func (q *Queries) ListProductsByIDs(ctx context.Context, ids []pgtype.UUID) ([]ListProductsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listProductsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByIDsRow{}
	for rows.Next() {
		var i ListProductsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.ImageUrl,
			&i.IsActive,
			&i.StockQuantity,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsForPicker = `-- name: SearchProductsForPicker :many

SELECT p.id, p.name, p.slug, p.sku, p.price, p.image_url, p.is_active,
       p.stock_quantity, c.name AS category_name
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE ($3::text IS NULL
       OR p.name ILIKE '%' || $3::text || '%'
       OR p.sku ILIKE '%' || $3::text || '%')
ORDER BY p.name ASC
LIMIT $1 OFFSET $2
`

type SearchProductsForPickerParams struct {
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
	Keyword pgtype.Text `db:"keyword" json:"keyword"`
}

type SearchProductsForPickerRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	Name          string         `db:"name" json:"name"`
	Slug          string         `db:"slug" json:"slug"`
	Sku           pgtype.Text    `db:"sku" json:"sku"`
	Price         pgtype.Numeric `db:"price" json:"price"`
	ImageUrl      pgtype.Text    `db:"image_url" json:"image_url"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	StockQuantity int32          `db:"stock_quantity" json:"stock_quantity"`
	CategoryName  string         `db:"category_name" json:"category_name"`
}

// ---------------------------------------------------------------------------
// Admin product picker
// ---------------------------------------------------------------------------
// Backs the collection product selector. Paginated and searched server-side so
// the browser never loads the whole catalogue. Matches name or SKU.
func (q *Queries) SearchProductsForPicker(ctx context.Context, arg SearchProductsForPickerParams) ([]SearchProductsForPickerRow, error) {
	rows, err := q.db.Query(ctx, searchProductsForPicker, arg.Limit, arg.Offset, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsForPickerRow{}
	for rows.Next() {
		var i SearchProductsForPickerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Sku,
			&i.Price,
			&i.ImageUrl,
			&i.IsActive,
			&i.StockQuantity,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $2, slug = $3, description = $4, image_url = $5,
    is_active = $6, is_featured = $7, sort_order = $8,
    meta_title = $9, meta_description = $10, meta_keywords = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, image_url, is_active, is_featured, sort_order, meta_title, meta_description, meta_keywords, created_at, updated_at
`

type UpdateCollectionParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Slug            string      `db:"slug" json:"slug"`
	Description     pgtype.Text `db:"description" json:"description"`
	ImageUrl        pgtype.Text `db:"image_url" json:"image_url"`
	IsActive        bool        `db:"is_active" json:"is_active"`
	IsFeatured      bool        `db:"is_featured" json:"is_featured"`
	SortOrder       int32       `db:"sort_order" json:"sort_order"`
	MetaTitle       pgtype.Text `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text `db:"meta_description" json:"meta_description"`
	MetaKeywords    pgtype.Text `db:"meta_keywords" json:"meta_keywords"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollection,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.IsActive,
		arg.IsFeatured,
		arg.SortOrder,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.MetaKeywords,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.SortOrder,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.MetaKeywords,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
