// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: coupons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCouponRedemptionsByUser = `-- name: CountCouponRedemptionsByUser :one
SELECT COUNT(*) FROM coupon_redemptions
WHERE coupon_id = $1 AND user_id = $2
`

type CountCouponRedemptionsByUserParams struct {
	CouponID pgtype.UUID `db:"coupon_id" json:"coupon_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) CountCouponRedemptionsByUser(ctx context.Context, arg CountCouponRedemptionsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponRedemptionsByUser, arg.CouponID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCouponsByCode = `-- name: CountCouponsByCode :one
SELECT COUNT(*) FROM coupons
WHERE code = $1
  AND ($2::uuid IS NULL OR id <> $2::uuid)
`

type CountCouponsByCodeParams struct {
	Code      string      `db:"code" json:"code"`
	ExcludeID pgtype.UUID `db:"exclude_id" json:"exclude_id"`
}

// Uniqueness check for the admin form. sqlc.narg('exclude_id') is the coupon
// being edited, so saving it without changing the code is not a conflict.
func (q *Queries) CountCouponsByCode(ctx context.Context, arg CountCouponsByCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponsByCode, arg.Code, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    code, description, is_active,
    discount_type, discount_value, max_discount_amount,
    min_order_amount, min_order_quantity,
    max_uses, max_uses_per_customer,
    starts_at, ends_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10,
    $11, $12
)
RETURNING id, code, description, is_active, discount_type, discount_value, max_discount_amount, min_order_amount, min_order_quantity, max_uses, max_uses_per_customer, used_count, starts_at, ends_at, created_at, updated_at
`

type CreateCouponParams struct {
	Code               string             `db:"code" json:"code"`
	Description        string             `db:"description" json:"description"`
	IsActive           bool               `db:"is_active" json:"is_active"`
	DiscountType       string             `db:"discount_type" json:"discount_type"`
	DiscountValue      pgtype.Numeric     `db:"discount_value" json:"discount_value"`
	MaxDiscountAmount  pgtype.Numeric     `db:"max_discount_amount" json:"max_discount_amount"`
	MinOrderAmount     pgtype.Numeric     `db:"min_order_amount" json:"min_order_amount"`
	MinOrderQuantity   int32              `db:"min_order_quantity" json:"min_order_quantity"`
	MaxUses            pgtype.Int4        `db:"max_uses" json:"max_uses"`
	MaxUsesPerCustomer pgtype.Int4        `db:"max_uses_per_customer" json:"max_uses_per_customer"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.Code,
		arg.Description,
		arg.IsActive,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MaxDiscountAmount,
		arg.MinOrderAmount,
		arg.MinOrderQuantity,
		arg.MaxUses,
		arg.MaxUsesPerCustomer,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MaxDiscountAmount,
		&i.MinOrderAmount,
		&i.MinOrderQuantity,
		&i.MaxUses,
		&i.MaxUsesPerCustomer,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCouponRedemption = `-- name: CreateCouponRedemption :one
INSERT INTO coupon_redemptions (coupon_id, user_id, order_id, discount_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, coupon_id, user_id, order_id, discount_amount, created_at
`

type CreateCouponRedemptionParams struct {
	CouponID       pgtype.UUID    `db:"coupon_id" json:"coupon_id"`
	UserID         pgtype.UUID    `db:"user_id" json:"user_id"`
	OrderID        pgtype.UUID    `db:"order_id" json:"order_id"`
	DiscountAmount pgtype.Numeric `db:"discount_amount" json:"discount_amount"`
}

func (q *Queries) CreateCouponRedemption(ctx context.Context, arg CreateCouponRedemptionParams) (CouponRedemption, error) {
	row := q.db.QueryRow(ctx, createCouponRedemption,
		arg.CouponID,
		arg.UserID,
		arg.OrderID,
		arg.DiscountAmount,
	)
	var i CouponRedemption
	err := row.Scan(
		&i.ID,
		&i.CouponID,
		&i.UserID,
		&i.OrderID,
		&i.DiscountAmount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :exec
DELETE FROM coupons WHERE id = $1
`

func (q *Queries) DeleteCoupon(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoupon, id)
	return err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, description, is_active, discount_type, discount_value, max_discount_amount, min_order_amount, min_order_quantity, max_uses, max_uses_per_customer, used_count, starts_at, ends_at, created_at, updated_at FROM coupons WHERE code = $1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MaxDiscountAmount,
		&i.MinOrderAmount,
		&i.MinOrderQuantity,
		&i.MaxUses,
		&i.MaxUsesPerCustomer,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByID = `-- name: GetCouponByID :one
SELECT id, code, description, is_active, discount_type, discount_value, max_discount_amount, min_order_amount, min_order_quantity, max_uses, max_uses_per_customer, used_count, starts_at, ends_at, created_at, updated_at FROM coupons WHERE id = $1
`

func (q *Queries) GetCouponByID(ctx context.Context, id pgtype.UUID) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByID, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MaxDiscountAmount,
		&i.MinOrderAmount,
		&i.MinOrderQuantity,
		&i.MaxUses,
		&i.MaxUsesPerCustomer,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCouponUsedCount = `-- name: IncrementCouponUsedCount :exec
UPDATE coupons SET used_count = used_count + 1 WHERE id = $1
`

func (q *Queries) IncrementCouponUsedCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementCouponUsedCount, id)
	return err
}

const listCoupons = `-- name: ListCoupons :many
SELECT id, code, description, is_active, discount_type, discount_value, max_discount_amount, min_order_amount, min_order_quantity, max_uses, max_uses_per_customer, used_count, starts_at, ends_at, created_at, updated_at FROM coupons
ORDER BY created_at DESC
`

func (q *Queries) ListCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.DiscountType,
			&i.DiscountValue,
			&i.MaxDiscountAmount,
			&i.MinOrderAmount,
			&i.MinOrderQuantity,
			&i.MaxUses,
			&i.MaxUsesPerCustomer,
			&i.UsedCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoupon = `-- name: UpdateCoupon :one
UPDATE coupons SET
    code = $2,
    description = $3,
    is_active = $4,
    discount_type = $5,
    discount_value = $6,
    max_discount_amount = $7,
    min_order_amount = $8,
    min_order_quantity = $9,
    max_uses = $10,
    max_uses_per_customer = $11,
    starts_at = $12,
    ends_at = $13
WHERE id = $1
RETURNING id, code, description, is_active, discount_type, discount_value, max_discount_amount, min_order_amount, min_order_quantity, max_uses, max_uses_per_customer, used_count, starts_at, ends_at, created_at, updated_at
`

type UpdateCouponParams struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Code               string             `db:"code" json:"code"`
	Description        string             `db:"description" json:"description"`
	IsActive           bool               `db:"is_active" json:"is_active"`
	DiscountType       string             `db:"discount_type" json:"discount_type"`
	DiscountValue      pgtype.Numeric     `db:"discount_value" json:"discount_value"`
	MaxDiscountAmount  pgtype.Numeric     `db:"max_discount_amount" json:"max_discount_amount"`
	MinOrderAmount     pgtype.Numeric     `db:"min_order_amount" json:"min_order_amount"`
	MinOrderQuantity   int32              `db:"min_order_quantity" json:"min_order_quantity"`
	MaxUses            pgtype.Int4        `db:"max_uses" json:"max_uses"`
	MaxUsesPerCustomer pgtype.Int4        `db:"max_uses_per_customer" json:"max_uses_per_customer"`
	StartsAt           pgtype.Timestamptz `db:"starts_at" json:"starts_at"`
	EndsAt             pgtype.Timestamptz `db:"ends_at" json:"ends_at"`
}

// used_count is deliberately absent: editing a coupon must never reset the
// redemptions already recorded against it.
func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, updateCoupon,
		arg.ID,
		arg.Code,
		arg.Description,
		arg.IsActive,
		arg.DiscountType,
		arg.DiscountValue,
		arg.MaxDiscountAmount,
		arg.MinOrderAmount,
		arg.MinOrderQuantity,
		arg.MaxUses,
		arg.MaxUsesPerCustomer,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.DiscountType,
		&i.DiscountValue,
		&i.MaxDiscountAmount,
		&i.MinOrderAmount,
		&i.MinOrderQuantity,
		&i.MaxUses,
		&i.MaxUsesPerCustomer,
		&i.UsedCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
