// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPending    OrderStatus = "pending"
	OrderStatusConfirmed  OrderStatus = "confirmed"
	OrderStatusProcessing OrderStatus = "processing"
	OrderStatusShipped    OrderStatus = "shipped"
	OrderStatusDelivered  OrderStatus = "delivered"
	OrderStatusCancelled  OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Address struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	Label        string             `db:"label" json:"label"`
	FirstName    string             `db:"first_name" json:"first_name"`
	LastName     string             `db:"last_name" json:"last_name"`
	Company      pgtype.Text        `db:"company" json:"company"`
	AddressLine1 string             `db:"address_line1" json:"address_line1"`
	AddressLine2 pgtype.Text        `db:"address_line2" json:"address_line2"`
	City         string             `db:"city" json:"city"`
	State        string             `db:"state" json:"state"`
	PostalCode   string             `db:"postal_code" json:"postal_code"`
	Country      string             `db:"country" json:"country"`
	Phone        pgtype.Text        `db:"phone" json:"phone"`
	IsDefault    bool               `db:"is_default" json:"is_default"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Attribute struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	Type       string             `db:"type" json:"type"`
	IsRequired bool               `db:"is_required" json:"is_required"`
	IsVariant  bool               `db:"is_variant" json:"is_variant"`
	SortOrder  int32              `db:"sort_order" json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AttributeOption struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	AttributeID pgtype.UUID        `db:"attribute_id" json:"attribute_id"`
	Value       string             `db:"value" json:"value"`
	SortOrder   int32              `db:"sort_order" json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Category struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ParentID    pgtype.UUID        `db:"parent_id" json:"parent_id"`
	Name        string             `db:"name" json:"name"`
	Slug        string             `db:"slug" json:"slug"`
	Description pgtype.Text        `db:"description" json:"description"`
	ImageUrl    pgtype.Text        `db:"image_url" json:"image_url"`
	SortOrder   int32              `db:"sort_order" json:"sort_order"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Order struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Status             OrderStatus        `db:"status" json:"status"`
	Total              pgtype.Numeric     `db:"total" json:"total"`
	Subtotal           pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric     `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric     `db:"discount" json:"discount"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	ShippingName       string             `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string             `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string             `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text        `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string             `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string             `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text        `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text        `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text        `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text        `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text        `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text        `db:"billing_country" json:"billing_country"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrderItem struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OrderID     pgtype.UUID        `db:"order_id" json:"order_id"`
	ProductID   pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID   pgtype.UUID        `db:"variant_id" json:"variant_id"`
	ProductName string             `db:"product_name" json:"product_name"`
	VariantName pgtype.Text        `db:"variant_name" json:"variant_name"`
	Quantity    int32              `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric     `db:"unit_price" json:"unit_price"`
	Total       pgtype.Numeric     `db:"total" json:"total"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Product struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	Name              string             `db:"name" json:"name"`
	Slug              string             `db:"slug" json:"slug"`
	Description       pgtype.Text        `db:"description" json:"description"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice    pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku               pgtype.Text        `db:"sku" json:"sku"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	IsFeatured        bool               `db:"is_featured" json:"is_featured"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight            pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle         pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription   pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ShortDescription  pgtype.Text        `db:"short_description" json:"short_description"`
	Brand             pgtype.Text        `db:"brand" json:"brand"`
	Tags              []string           `db:"tags" json:"tags"`
	CostPrice         pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	TrackInventory    bool               `db:"track_inventory" json:"track_inventory"`
	AllowBackorders   bool               `db:"allow_backorders" json:"allow_backorders"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	Length            pgtype.Numeric     `db:"length" json:"length"`
	Width             pgtype.Numeric     `db:"width" json:"width"`
	Height            pgtype.Numeric     `db:"height" json:"height"`
	MetaKeywords      pgtype.Text        `db:"meta_keywords" json:"meta_keywords"`
	SortOrder         int32              `db:"sort_order" json:"sort_order"`
}

type ProductAttribute struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	ProductID   pgtype.UUID        `db:"product_id" json:"product_id"`
	AttributeID pgtype.UUID        `db:"attribute_id" json:"attribute_id"`
	OptionID    pgtype.UUID        `db:"option_id" json:"option_id"`
	Value       pgtype.Text        `db:"value" json:"value"`
	SortOrder   int32              `db:"sort_order" json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductImage struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ProductID pgtype.UUID        `db:"product_id" json:"product_id"`
	Url       string             `db:"url" json:"url"`
	AltText   pgtype.Text        `db:"alt_text" json:"alt_text"`
	SortOrder int32              `db:"sort_order" json:"sort_order"`
	IsPrimary bool               `db:"is_primary" json:"is_primary"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductVariant struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	ProductID     pgtype.UUID        `db:"product_id" json:"product_id"`
	Name          string             `db:"name" json:"name"`
	Sku           pgtype.Text        `db:"sku" json:"sku"`
	Price         pgtype.Numeric     `db:"price" json:"price"`
	StockQuantity int32              `db:"stock_quantity" json:"stock_quantity"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Barcode       pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl      pgtype.Text        `db:"image_url" json:"image_url"`
	Weight        pgtype.Numeric     `db:"weight" json:"weight"`
	Options       []byte             `db:"options" json:"options"`
	SortOrder     int32              `db:"sort_order" json:"sort_order"`
}

type StoreSetting struct {
	ID                    int32              `db:"id" json:"id"`
	TaxRate               pgtype.Numeric     `db:"tax_rate" json:"tax_rate"`
	ShippingCost          pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	FreeShippingThreshold pgtype.Numeric     `db:"free_shipping_threshold" json:"free_shipping_threshold"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
