// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, variant_id, product_name, variant_name, quantity, unit_price, total)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, order_id, product_id, variant_id, product_name, variant_name, quantity, unit_price, total, created_at
`

type CreateOrderItemParams struct {
	OrderID     pgtype.UUID    `db:"order_id" json:"order_id"`
	ProductID   pgtype.UUID    `db:"product_id" json:"product_id"`
	VariantID   pgtype.UUID    `db:"variant_id" json:"variant_id"`
	ProductName string         `db:"product_name" json:"product_name"`
	VariantName pgtype.Text    `db:"variant_name" json:"variant_name"`
	Quantity    int32          `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	Total       pgtype.Numeric `db:"total" json:"total"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.ProductName,
		arg.VariantName,
		arg.Quantity,
		arg.UnitPrice,
		arg.Total,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Quantity,
		&i.UnitPrice,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items WHERE order_id = $1
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getOrderItemByProduct = `-- name: GetOrderItemByProduct :many
SELECT oi.id, oi.order_id, oi.product_id, oi.variant_id, oi.product_name, oi.variant_name, oi.quantity, oi.unit_price, oi.total, oi.created_at, o.status AS order_status
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.product_id = $1
ORDER BY oi.created_at DESC
`

type GetOrderItemByProductRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	OrderID     pgtype.UUID        `db:"order_id" json:"order_id"`
	ProductID   pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID   pgtype.UUID        `db:"variant_id" json:"variant_id"`
	ProductName string             `db:"product_name" json:"product_name"`
	VariantName pgtype.Text        `db:"variant_name" json:"variant_name"`
	Quantity    int32              `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric     `db:"unit_price" json:"unit_price"`
	Total       pgtype.Numeric     `db:"total" json:"total"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	OrderStatus OrderStatus        `db:"order_status" json:"order_status"`
}

func (q *Queries) GetOrderItemByProduct(ctx context.Context, productID pgtype.UUID) ([]GetOrderItemByProductRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemByProductRow{}
	for rows.Next() {
		var i GetOrderItemByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Quantity,
			&i.UnitPrice,
			&i.Total,
			&i.CreatedAt,
			&i.OrderStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemCountByProduct = `-- name: GetOrderItemCountByProduct :one
SELECT COALESCE(SUM(quantity), 0)::bigint AS total_sold
FROM order_items
WHERE product_id = $1
`

func (q *Queries) GetOrderItemCountByProduct(ctx context.Context, productID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderItemCountByProduct, productID)
	var total_sold int64
	err := row.Scan(&total_sold)
	return total_sold, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT oi.id, oi.order_id, oi.product_id, oi.variant_id, oi.product_name, oi.variant_name, oi.quantity, oi.unit_price, oi.total, oi.created_at, p.slug AS product_slug, p.image_url AS product_image_url
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
ORDER BY oi.created_at ASC
`

type GetOrderItemsByOrderIDRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	OrderID         pgtype.UUID        `db:"order_id" json:"order_id"`
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	VariantID       pgtype.UUID        `db:"variant_id" json:"variant_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	VariantName     pgtype.Text        `db:"variant_name" json:"variant_name"`
	Quantity        int32              `db:"quantity" json:"quantity"`
	UnitPrice       pgtype.Numeric     `db:"unit_price" json:"unit_price"`
	Total           pgtype.Numeric     `db:"total" json:"total"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProductSlug     string             `db:"product_slug" json:"product_slug"`
	ProductImageUrl pgtype.Text        `db:"product_image_url" json:"product_image_url"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsByOrderIDRow{}
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Quantity,
			&i.UnitPrice,
			&i.Total,
			&i.CreatedAt,
			&i.ProductSlug,
			&i.ProductImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSellingProducts = `-- name: GetTopSellingProducts :many
SELECT
    p.id,
    p.name,
    p.slug,
    p.price,
    p.image_url,
    SUM(oi.quantity)::bigint AS total_sold,
    SUM(oi.total)::decimal AS total_revenue
FROM order_items oi
JOIN products p ON p.id = oi.product_id
JOIN orders o ON o.id = oi.order_id
WHERE o.status != 'cancelled'
GROUP BY p.id, p.name, p.slug, p.price, p.image_url
ORDER BY total_sold DESC
LIMIT $1
`

type GetTopSellingProductsRow struct {
	ID           pgtype.UUID    `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	Slug         string         `db:"slug" json:"slug"`
	Price        pgtype.Numeric `db:"price" json:"price"`
	ImageUrl     pgtype.Text    `db:"image_url" json:"image_url"`
	TotalSold    int64          `db:"total_sold" json:"total_sold"`
	TotalRevenue pgtype.Numeric `db:"total_revenue" json:"total_revenue"`
}

func (q *Queries) GetTopSellingProducts(ctx context.Context, limit int32) ([]GetTopSellingProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopSellingProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopSellingProductsRow{}
	for rows.Next() {
		var i GetTopSellingProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Price,
			&i.ImageUrl,
			&i.TotalSold,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
