// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllOrders = `-- name: CountAllOrders :one
SELECT COUNT(*) FROM orders
`

func (q *Queries) CountAllOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByStatus = `-- name: CountOrdersByStatus :one
SELECT COUNT(*) FROM orders WHERE status = $1
`

func (q *Queries) CountOrdersByStatus(ctx context.Context, status OrderStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) FROM orders WHERE user_id = $1
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total, subtotal, tax, shipping_cost, discount, notes, shipping_name, shipping_address, shipping_city, shipping_state, shipping_postal_code, shipping_country, billing_name, billing_address, billing_city, billing_state, billing_postal_code, billing_country)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, user_id, status, total, subtotal, tax, shipping_cost, discount, notes, shipping_name, shipping_address, shipping_city, shipping_state, shipping_postal_code, shipping_country, billing_name, billing_address, billing_city, billing_state, billing_postal_code, billing_country, created_at, updated_at
`

type CreateOrderParams struct {
	UserID             pgtype.UUID    `db:"user_id" json:"user_id"`
	Status             OrderStatus    `db:"status" json:"status"`
	Total              pgtype.Numeric `db:"total" json:"total"`
	Subtotal           pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric `db:"discount" json:"discount"`
	Notes              pgtype.Text    `db:"notes" json:"notes"`
	ShippingName       string         `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string         `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string         `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text    `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string         `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string         `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text    `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text    `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text    `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text    `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text    `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text    `db:"billing_country" json:"billing_country"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.Total,
		arg.Subtotal,
		arg.Tax,
		arg.ShippingCost,
		arg.Discount,
		arg.Notes,
		arg.ShippingName,
		arg.ShippingAddress,
		arg.ShippingCity,
		arg.ShippingState,
		arg.ShippingPostalCode,
		arg.ShippingCountry,
		arg.BillingName,
		arg.BillingAddress,
		arg.BillingCity,
		arg.BillingState,
		arg.BillingPostalCode,
		arg.BillingCountry,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Subtotal,
		&i.Tax,
		&i.ShippingCost,
		&i.Discount,
		&i.Notes,
		&i.ShippingName,
		&i.ShippingAddress,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.BillingName,
		&i.BillingAddress,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT o.id, o.user_id, o.status, o.total, o.subtotal, o.tax, o.shipping_cost, o.discount, o.notes, o.shipping_name, o.shipping_address, o.shipping_city, o.shipping_state, o.shipping_postal_code, o.shipping_country, o.billing_name, o.billing_address, o.billing_city, o.billing_state, o.billing_postal_code, o.billing_country, o.created_at, o.updated_at,
    u.name AS customer_name,
    u.email AS customer_email
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.id = $1
`

type GetOrderByIDRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Status             OrderStatus        `db:"status" json:"status"`
	Total              pgtype.Numeric     `db:"total" json:"total"`
	Subtotal           pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric     `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric     `db:"discount" json:"discount"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	ShippingName       string             `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string             `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string             `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text        `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string             `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string             `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text        `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text        `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text        `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text        `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text        `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text        `db:"billing_country" json:"billing_country"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName       string             `db:"customer_name" json:"customer_name"`
	CustomerEmail      string             `db:"customer_email" json:"customer_email"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Subtotal,
		&i.Tax,
		&i.ShippingCost,
		&i.Discount,
		&i.Notes,
		&i.ShippingName,
		&i.ShippingAddress,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.BillingName,
		&i.BillingAddress,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.CustomerEmail,
	)
	return i, err
}

const getOrderSummary = `-- name: GetOrderSummary :one
SELECT
    COUNT(*)::bigint AS total_orders,
    COALESCE(SUM(total), 0)::decimal AS total_revenue,
    COALESCE(AVG(total), 0)::decimal AS average_order_value,
    COUNT(DISTINCT user_id)::bigint AS unique_customers
FROM orders
WHERE status != 'cancelled'
`

type GetOrderSummaryRow struct {
	TotalOrders       int64          `db:"total_orders" json:"total_orders"`
	TotalRevenue      pgtype.Numeric `db:"total_revenue" json:"total_revenue"`
	AverageOrderValue pgtype.Numeric `db:"average_order_value" json:"average_order_value"`
	UniqueCustomers   int64          `db:"unique_customers" json:"unique_customers"`
}

func (q *Queries) GetOrderSummary(ctx context.Context) (GetOrderSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOrderSummary)
	var i GetOrderSummaryRow
	err := row.Scan(
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.AverageOrderValue,
		&i.UniqueCustomers,
	)
	return i, err
}

const getOrdersByDateRange = `-- name: GetOrdersByDateRange :many
SELECT o.id, o.user_id, o.status, o.total, o.subtotal, o.tax, o.shipping_cost, o.discount, o.notes, o.shipping_name, o.shipping_address, o.shipping_city, o.shipping_state, o.shipping_postal_code, o.shipping_country, o.billing_name, o.billing_address, o.billing_city, o.billing_state, o.billing_postal_code, o.billing_country, o.created_at, o.updated_at,
    u.name AS customer_name,
    u.email AS customer_email
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.created_at >= $1 AND o.created_at <= $2
ORDER BY o.created_at DESC
`

type GetOrdersByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `db:"created_at_2" json:"created_at_2"`
}

type GetOrdersByDateRangeRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Status             OrderStatus        `db:"status" json:"status"`
	Total              pgtype.Numeric     `db:"total" json:"total"`
	Subtotal           pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric     `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric     `db:"discount" json:"discount"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	ShippingName       string             `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string             `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string             `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text        `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string             `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string             `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text        `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text        `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text        `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text        `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text        `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text        `db:"billing_country" json:"billing_country"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName       string             `db:"customer_name" json:"customer_name"`
	CustomerEmail      string             `db:"customer_email" json:"customer_email"`
}

func (q *Queries) GetOrdersByDateRange(ctx context.Context, arg GetOrdersByDateRangeParams) ([]GetOrdersByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrdersByDateRangeRow{}
	for rows.Next() {
		var i GetOrdersByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Subtotal,
			&i.Tax,
			&i.ShippingCost,
			&i.Discount,
			&i.Notes,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentOrders = `-- name: GetRecentOrders :many
SELECT o.id, o.user_id, o.status, o.total, o.subtotal, o.tax, o.shipping_cost, o.discount, o.notes, o.shipping_name, o.shipping_address, o.shipping_city, o.shipping_state, o.shipping_postal_code, o.shipping_country, o.billing_name, o.billing_address, o.billing_city, o.billing_state, o.billing_postal_code, o.billing_country, o.created_at, o.updated_at,
    u.name AS customer_name,
    u.email AS customer_email
FROM orders o
JOIN users u ON u.id = o.user_id
ORDER BY o.created_at DESC
LIMIT $1
`

type GetRecentOrdersRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Status             OrderStatus        `db:"status" json:"status"`
	Total              pgtype.Numeric     `db:"total" json:"total"`
	Subtotal           pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric     `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric     `db:"discount" json:"discount"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	ShippingName       string             `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string             `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string             `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text        `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string             `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string             `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text        `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text        `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text        `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text        `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text        `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text        `db:"billing_country" json:"billing_country"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName       string             `db:"customer_name" json:"customer_name"`
	CustomerEmail      string             `db:"customer_email" json:"customer_email"`
}

func (q *Queries) GetRecentOrders(ctx context.Context, limit int32) ([]GetRecentOrdersRow, error) {
	rows, err := q.db.Query(ctx, getRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentOrdersRow{}
	for rows.Next() {
		var i GetRecentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Subtotal,
			&i.Tax,
			&i.ShippingCost,
			&i.Discount,
			&i.Notes,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesByDay = `-- name: GetSalesByDay :many
SELECT
    DATE(created_at) AS date,
    COUNT(*)::bigint AS order_count,
    COALESCE(SUM(total), 0)::decimal AS revenue
FROM orders
WHERE status != 'cancelled'
  AND created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY date DESC
`

type GetSalesByDayRow struct {
	Date       pgtype.Date    `db:"date" json:"date"`
	OrderCount int64          `db:"order_count" json:"order_count"`
	Revenue    pgtype.Numeric `db:"revenue" json:"revenue"`
}

func (q *Queries) GetSalesByDay(ctx context.Context) ([]GetSalesByDayRow, error) {
	rows, err := q.db.Query(ctx, getSalesByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSalesByDayRow{}
	for rows.Next() {
		var i GetSalesByDayRow
		if err := rows.Scan(&i.Date, &i.OrderCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSales = `-- name: GetTotalSales :one
SELECT COALESCE(SUM(total), 0)::decimal AS total_sales
FROM orders
WHERE status != 'cancelled'
`

func (q *Queries) GetTotalSales(ctx context.Context) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalSales)
	var total_sales pgtype.Numeric
	err := row.Scan(&total_sales)
	return total_sales, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT o.id, o.user_id, o.status, o.total, o.subtotal, o.tax, o.shipping_cost, o.discount, o.notes, o.shipping_name, o.shipping_address, o.shipping_city, o.shipping_state, o.shipping_postal_code, o.shipping_country, o.billing_name, o.billing_address, o.billing_city, o.billing_state, o.billing_postal_code, o.billing_country, o.created_at, o.updated_at,
    u.name AS customer_name,
    u.email AS customer_email
FROM orders o
JOIN users u ON u.id = o.user_id
ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllOrdersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAllOrdersRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Status             OrderStatus        `db:"status" json:"status"`
	Total              pgtype.Numeric     `db:"total" json:"total"`
	Subtotal           pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric     `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric     `db:"discount" json:"discount"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	ShippingName       string             `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string             `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string             `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text        `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string             `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string             `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text        `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text        `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text        `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text        `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text        `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text        `db:"billing_country" json:"billing_country"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName       string             `db:"customer_name" json:"customer_name"`
	CustomerEmail      string             `db:"customer_email" json:"customer_email"`
}

func (q *Queries) ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]ListAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAllOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOrdersRow{}
	for rows.Next() {
		var i ListAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Subtotal,
			&i.Tax,
			&i.ShippingCost,
			&i.Discount,
			&i.Notes,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT o.id, o.user_id, o.status, o.total, o.subtotal, o.tax, o.shipping_cost, o.discount, o.notes, o.shipping_name, o.shipping_address, o.shipping_city, o.shipping_state, o.shipping_postal_code, o.shipping_country, o.billing_name, o.billing_address, o.billing_city, o.billing_state, o.billing_postal_code, o.billing_country, o.created_at, o.updated_at,
    u.name AS customer_name,
    u.email AS customer_email
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE o.status = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByStatusParams struct {
	Status OrderStatus `db:"status" json:"status"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type ListOrdersByStatusRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	UserID             pgtype.UUID        `db:"user_id" json:"user_id"`
	Status             OrderStatus        `db:"status" json:"status"`
	Total              pgtype.Numeric     `db:"total" json:"total"`
	Subtotal           pgtype.Numeric     `db:"subtotal" json:"subtotal"`
	Tax                pgtype.Numeric     `db:"tax" json:"tax"`
	ShippingCost       pgtype.Numeric     `db:"shipping_cost" json:"shipping_cost"`
	Discount           pgtype.Numeric     `db:"discount" json:"discount"`
	Notes              pgtype.Text        `db:"notes" json:"notes"`
	ShippingName       string             `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string             `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string             `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text        `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string             `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string             `db:"shipping_country" json:"shipping_country"`
	BillingName        pgtype.Text        `db:"billing_name" json:"billing_name"`
	BillingAddress     pgtype.Text        `db:"billing_address" json:"billing_address"`
	BillingCity        pgtype.Text        `db:"billing_city" json:"billing_city"`
	BillingState       pgtype.Text        `db:"billing_state" json:"billing_state"`
	BillingPostalCode  pgtype.Text        `db:"billing_postal_code" json:"billing_postal_code"`
	BillingCountry     pgtype.Text        `db:"billing_country" json:"billing_country"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName       string             `db:"customer_name" json:"customer_name"`
	CustomerEmail      string             `db:"customer_email" json:"customer_email"`
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]ListOrdersByStatusRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByStatusRow{}
	for rows.Next() {
		var i ListOrdersByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Subtotal,
			&i.Tax,
			&i.ShippingCost,
			&i.Discount,
			&i.Notes,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT o.id, o.user_id, o.status, o.total, o.subtotal, o.tax, o.shipping_cost, o.discount, o.notes, o.shipping_name, o.shipping_address, o.shipping_city, o.shipping_state, o.shipping_postal_code, o.shipping_country, o.billing_name, o.billing_address, o.billing_city, o.billing_state, o.billing_postal_code, o.billing_country, o.created_at, o.updated_at
FROM orders o
WHERE o.user_id = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Subtotal,
			&i.Tax,
			&i.ShippingCost,
			&i.Discount,
			&i.Notes,
			&i.ShippingName,
			&i.ShippingAddress,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.BillingName,
			&i.BillingAddress,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET status = $2, notes = $3, shipping_name = $4, shipping_address = $5, shipping_city = $6, shipping_state = $7, shipping_postal_code = $8, shipping_country = $9
WHERE id = $1
RETURNING id, user_id, status, total, subtotal, tax, shipping_cost, discount, notes, shipping_name, shipping_address, shipping_city, shipping_state, shipping_postal_code, shipping_country, billing_name, billing_address, billing_city, billing_state, billing_postal_code, billing_country, created_at, updated_at
`

type UpdateOrderParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	Status             OrderStatus `db:"status" json:"status"`
	Notes              pgtype.Text `db:"notes" json:"notes"`
	ShippingName       string      `db:"shipping_name" json:"shipping_name"`
	ShippingAddress    string      `db:"shipping_address" json:"shipping_address"`
	ShippingCity       string      `db:"shipping_city" json:"shipping_city"`
	ShippingState      pgtype.Text `db:"shipping_state" json:"shipping_state"`
	ShippingPostalCode string      `db:"shipping_postal_code" json:"shipping_postal_code"`
	ShippingCountry    string      `db:"shipping_country" json:"shipping_country"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.Status,
		arg.Notes,
		arg.ShippingName,
		arg.ShippingAddress,
		arg.ShippingCity,
		arg.ShippingState,
		arg.ShippingPostalCode,
		arg.ShippingCountry,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Subtotal,
		&i.Tax,
		&i.ShippingCost,
		&i.Discount,
		&i.Notes,
		&i.ShippingName,
		&i.ShippingAddress,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.BillingName,
		&i.BillingAddress,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $2 WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status OrderStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
