// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: product_images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, url, alt_text, sort_order, is_primary)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, product_id, url, alt_text, sort_order, is_primary, created_at
`

type CreateProductImageParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	Url       string      `db:"url" json:"url"`
	AltText   pgtype.Text `db:"alt_text" json:"alt_text"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
	IsPrimary bool        `db:"is_primary" json:"is_primary"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.Url,
		arg.AltText,
		arg.SortOrder,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const deleteProductImagesByProductID = `-- name: DeleteProductImagesByProductID :exec
DELETE FROM product_images WHERE product_id = $1
`

func (q *Queries) DeleteProductImagesByProductID(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImagesByProductID, productID)
	return err
}

const getPrimaryProductImage = `-- name: GetPrimaryProductImage :one
SELECT id, product_id, url, alt_text, sort_order, is_primary, created_at FROM product_images
WHERE product_id = $1 AND is_primary = true
LIMIT 1
`

func (q *Queries) GetPrimaryProductImage(ctx context.Context, productID pgtype.UUID) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getPrimaryProductImage, productID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, url, alt_text, sort_order, is_primary, created_at FROM product_images WHERE id = $1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id pgtype.UUID) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, alt_text, sort_order, is_primary, created_at FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID pgtype.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryProductImage = `-- name: SetPrimaryProductImage :exec
UPDATE product_images SET is_primary = false WHERE product_id = $1
`

func (q *Queries) SetPrimaryProductImage(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setPrimaryProductImage, productID)
	return err
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE product_images
SET url = $2, alt_text = $3, sort_order = $4, is_primary = $5
WHERE id = $1
RETURNING id, product_id, url, alt_text, sort_order, is_primary, created_at
`

type UpdateProductImageParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	Url       string      `db:"url" json:"url"`
	AltText   pgtype.Text `db:"alt_text" json:"alt_text"`
	SortOrder int32       `db:"sort_order" json:"sort_order"`
	IsPrimary bool        `db:"is_primary" json:"is_primary"`
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, updateProductImage,
		arg.ID,
		arg.Url,
		arg.AltText,
		arg.SortOrder,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}
