// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveProducts = `-- name: CountActiveProducts :one
SELECT COUNT(*) FROM products WHERE is_active = true
`

func (q *Queries) CountActiveProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProducts = `-- name: CountAllProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountAllProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilterProducts = `-- name: CountFilterProducts :one
SELECT COUNT(*)
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
  AND ($1::text IS NULL
       OR p.name ILIKE '%' || $1 || '%'
       OR p.description ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR c.slug = $2)
  AND ($3::numeric IS NULL OR p.price >= $3)
  AND ($4::numeric IS NULL OR p.price <= $4)
`

type CountFilterProductsParams struct {
	Search   pgtype.Text    `db:"search" json:"search"`
	Category pgtype.Text    `db:"category" json:"category"`
	MinPrice pgtype.Numeric `db:"min_price" json:"min_price"`
	MaxPrice pgtype.Numeric `db:"max_price" json:"max_price"`
}

func (q *Queries) CountFilterProducts(ctx context.Context, arg CountFilterProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilterProducts,
		arg.Search,
		arg.Category,
		arg.MinPrice,
		arg.MaxPrice,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true AND c.slug = $1
`

func (q *Queries) CountProductsByCategory(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCategory, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT COUNT(*) FROM products p
WHERE p.is_active = true
  AND (p.name ILIKE '%' || $1 || '%' OR p.description ILIKE '%' || $1 || '%')
`

func (q *Queries) CountSearchProducts(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProducts, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (category_id, name, slug, description, price, compare_at_price, sku, barcode, image_url, is_active, is_featured, stock_quantity, weight, meta_title, meta_description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, category_id, name, slug, description, price, compare_at_price, sku, barcode, image_url, is_active, is_featured, stock_quantity, weight, meta_title, meta_description, created_at, updated_at
`

type CreateProductParams struct {
	CategoryID      pgtype.UUID    `db:"category_id" json:"category_id"`
	Name            string         `db:"name" json:"name"`
	Slug            string         `db:"slug" json:"slug"`
	Description     pgtype.Text    `db:"description" json:"description"`
	Price           pgtype.Numeric `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text    `db:"sku" json:"sku"`
	Barcode         pgtype.Text    `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text    `db:"image_url" json:"image_url"`
	IsActive        bool           `db:"is_active" json:"is_active"`
	IsFeatured      bool           `db:"is_featured" json:"is_featured"`
	StockQuantity   int32          `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text    `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text    `db:"meta_description" json:"meta_description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.CompareAtPrice,
		arg.Sku,
		arg.Barcode,
		arg.ImageUrl,
		arg.IsActive,
		arg.IsFeatured,
		arg.StockQuantity,
		arg.Weight,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.StockQuantity,
		&i.Weight,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const filterProducts = `-- name: FilterProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
  AND ($3::text IS NULL
       OR p.name ILIKE '%' || $3 || '%'
       OR p.description ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR c.slug = $4)
  AND ($5::numeric IS NULL OR p.price >= $5)
  AND ($6::numeric IS NULL OR p.price <= $6)
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type FilterProductsParams struct {
	Limit    int32          `db:"limit" json:"limit"`
	Offset   int32          `db:"offset" json:"offset"`
	Search   pgtype.Text    `db:"search" json:"search"`
	Category pgtype.Text    `db:"category" json:"category"`
	MinPrice pgtype.Numeric `db:"min_price" json:"min_price"`
	MaxPrice pgtype.Numeric `db:"max_price" json:"max_price"`
}

type FilterProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) FilterProducts(ctx context.Context, arg FilterProductsParams) ([]FilterProductsRow, error) {
	rows, err := q.db.Query(ctx, filterProducts,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Category,
		arg.MinPrice,
		arg.MaxPrice,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterProductsRow{}
	for rows.Next() {
		var i FilterProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true AND p.stock_quantity <= $1
ORDER BY p.stock_quantity ASC
LIMIT $2
`

type GetLowStockProductsParams struct {
	StockQuantity int32 `db:"stock_quantity" json:"stock_quantity"`
	Limit         int32 `db:"limit" json:"limit"`
}

type GetLowStockProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) GetLowStockProducts(ctx context.Context, arg GetLowStockProductsParams) ([]GetLowStockProductsRow, error) {
	rows, err := q.db.Query(ctx, getLowStockProducts, arg.StockQuantity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLowStockProductsRow{}
	for rows.Next() {
		var i GetLowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.barcode = $1
`

type GetProductByBarcodeRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) GetProductByBarcode(ctx context.Context, barcode pgtype.Text) (GetProductByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, barcode)
	var i GetProductByBarcodeRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.StockQuantity,
		&i.Weight,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.id = $1
`

type GetProductByIDRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.StockQuantity,
		&i.Weight,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.sku = $1
`

type GetProductBySKURow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, sku pgtype.Text) (GetProductBySKURow, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i GetProductBySKURow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.StockQuantity,
		&i.Weight,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.slug = $1
`

type GetProductBySlugRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.StockQuantity,
		&i.Weight,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAllProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) ListAllProducts(ctx context.Context, arg ListAllProductsParams) ([]ListAllProductsRow, error) {
	rows, err := q.db.Query(ctx, listAllProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProductsRow{}
	for rows.Next() {
		var i ListAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true AND p.is_featured = true
ORDER BY p.created_at DESC
LIMIT $1
`

type ListFeaturedProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) ListFeaturedProducts(ctx context.Context, limit int32) ([]ListFeaturedProductsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeaturedProductsRow{}
	for rows.Next() {
		var i ListFeaturedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestProducts = `-- name: ListNewestProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
ORDER BY p.created_at DESC
LIMIT $1
`

type ListNewestProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) ListNewestProducts(ctx context.Context, limit int32) ([]ListNewestProductsRow, error) {
	rows, err := q.db.Query(ctx, listNewestProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNewestProductsRow{}
	for rows.Next() {
		var i ListNewestProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true AND c.slug = $1
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	Slug   string `db:"slug" json:"slug"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type ListProductsByCategoryRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCategoryRow{}
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByPriceRange = `-- name: ListProductsByPriceRange :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
  AND p.price >= $1 AND p.price <= $2
ORDER BY p.price ASC
LIMIT $3 OFFSET $4
`

type ListProductsByPriceRangeParams struct {
	Price   pgtype.Numeric `db:"price" json:"price"`
	Price_2 pgtype.Numeric `db:"price_2" json:"price_2"`
	Limit   int32          `db:"limit" json:"limit"`
	Offset  int32          `db:"offset" json:"offset"`
}

type ListProductsByPriceRangeRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) ListProductsByPriceRange(ctx context.Context, arg ListProductsByPriceRangeParams) ([]ListProductsByPriceRangeRow, error) {
	rows, err := q.db.Query(ctx, listProductsByPriceRange,
		arg.Price,
		arg.Price_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByPriceRangeRow{}
	for rows.Next() {
		var i ListProductsByPriceRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT p.id, p.category_id, p.name, p.slug, p.description, p.price, p.compare_at_price, p.sku, p.barcode, p.image_url, p.is_active, p.is_featured, p.stock_quantity, p.weight, p.meta_title, p.meta_description, p.created_at, p.updated_at, c.name AS category_name, c.slug AS category_slug
FROM products p
JOIN categories c ON c.id = p.category_id
WHERE p.is_active = true
  AND (p.name ILIKE '%' || $1 || '%' OR p.description ILIKE '%' || $1 || '%')
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type SearchProductsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CategoryID      pgtype.UUID        `db:"category_id" json:"category_id"`
	Name            string             `db:"name" json:"name"`
	Slug            string             `db:"slug" json:"slug"`
	Description     pgtype.Text        `db:"description" json:"description"`
	Price           pgtype.Numeric     `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric     `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text        `db:"sku" json:"sku"`
	Barcode         pgtype.Text        `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text        `db:"image_url" json:"image_url"`
	IsActive        bool               `db:"is_active" json:"is_active"`
	IsFeatured      bool               `db:"is_featured" json:"is_featured"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric     `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text        `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text        `db:"meta_description" json:"meta_description"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CategoryName    string             `db:"category_name" json:"category_name"`
	CategorySlug    string             `db:"category_slug" json:"category_slug"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductsRow{}
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.CompareAtPrice,
			&i.Sku,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.IsFeatured,
			&i.StockQuantity,
			&i.Weight,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $2, name = $3, slug = $4, description = $5, price = $6, compare_at_price = $7, sku = $8, barcode = $9, image_url = $10, is_active = $11, is_featured = $12, stock_quantity = $13, weight = $14, meta_title = $15, meta_description = $16
WHERE id = $1
RETURNING id, category_id, name, slug, description, price, compare_at_price, sku, barcode, image_url, is_active, is_featured, stock_quantity, weight, meta_title, meta_description, created_at, updated_at
`

type UpdateProductParams struct {
	ID              pgtype.UUID    `db:"id" json:"id"`
	CategoryID      pgtype.UUID    `db:"category_id" json:"category_id"`
	Name            string         `db:"name" json:"name"`
	Slug            string         `db:"slug" json:"slug"`
	Description     pgtype.Text    `db:"description" json:"description"`
	Price           pgtype.Numeric `db:"price" json:"price"`
	CompareAtPrice  pgtype.Numeric `db:"compare_at_price" json:"compare_at_price"`
	Sku             pgtype.Text    `db:"sku" json:"sku"`
	Barcode         pgtype.Text    `db:"barcode" json:"barcode"`
	ImageUrl        pgtype.Text    `db:"image_url" json:"image_url"`
	IsActive        bool           `db:"is_active" json:"is_active"`
	IsFeatured      bool           `db:"is_featured" json:"is_featured"`
	StockQuantity   int32          `db:"stock_quantity" json:"stock_quantity"`
	Weight          pgtype.Numeric `db:"weight" json:"weight"`
	MetaTitle       pgtype.Text    `db:"meta_title" json:"meta_title"`
	MetaDescription pgtype.Text    `db:"meta_description" json:"meta_description"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.CompareAtPrice,
		arg.Sku,
		arg.Barcode,
		arg.ImageUrl,
		arg.IsActive,
		arg.IsFeatured,
		arg.StockQuantity,
		arg.Weight,
		arg.MetaTitle,
		arg.MetaDescription,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.CompareAtPrice,
		&i.Sku,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.IsFeatured,
		&i.StockQuantity,
		&i.Weight,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products SET stock_quantity = $2 WHERE id = $1
`

type UpdateProductStockParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	StockQuantity int32       `db:"stock_quantity" json:"stock_quantity"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.StockQuantity)
	return err
}
