// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: product_variants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (product_id, name, sku, price, stock_quantity, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, name, sku, price, stock_quantity, is_active, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID     pgtype.UUID    `db:"product_id" json:"product_id"`
	Name          string         `db:"name" json:"name"`
	Sku           pgtype.Text    `db:"sku" json:"sku"`
	Price         pgtype.Numeric `db:"price" json:"price"`
	StockQuantity int32          `db:"stock_quantity" json:"stock_quantity"`
	IsActive      bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.Name,
		arg.Sku,
		arg.Price,
		arg.StockQuantity,
		arg.IsActive,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants WHERE id = $1
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductVariant, id)
	return err
}

const deleteVariantsByProductID = `-- name: DeleteVariantsByProductID :exec
DELETE FROM product_variants WHERE product_id = $1
`

func (q *Queries) DeleteVariantsByProductID(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantsByProductID, productID)
	return err
}

const getProductVariantByID = `-- name: GetProductVariantByID :one
SELECT id, product_id, name, sku, price, stock_quantity, is_active, created_at, updated_at FROM product_variants WHERE id = $1
`

func (q *Queries) GetProductVariantByID(ctx context.Context, id pgtype.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getProductVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantBySKU = `-- name: GetVariantBySKU :one
SELECT id, product_id, name, sku, price, stock_quantity, is_active, created_at, updated_at FROM product_variants WHERE sku = $1
`

func (q *Queries) GetVariantBySKU(ctx context.Context, sku pgtype.Text) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantBySKU, sku)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProductVariants = `-- name: ListActiveProductVariants :many
SELECT id, product_id, name, sku, price, stock_quantity, is_active, created_at, updated_at FROM product_variants
WHERE product_id = $1 AND is_active = true
ORDER BY created_at ASC
`

func (q *Queries) ListActiveProductVariants(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listActiveProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.StockQuantity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, product_id, name, sku, price, stock_quantity, is_active, created_at, updated_at FROM product_variants
WHERE product_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProductVariants(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.StockQuantity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants
SET name = $2, sku = $3, price = $4, stock_quantity = $5, is_active = $6
WHERE id = $1
RETURNING id, product_id, name, sku, price, stock_quantity, is_active, created_at, updated_at
`

type UpdateProductVariantParams struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	Name          string         `db:"name" json:"name"`
	Sku           pgtype.Text    `db:"sku" json:"sku"`
	Price         pgtype.Numeric `db:"price" json:"price"`
	StockQuantity int32          `db:"stock_quantity" json:"stock_quantity"`
	IsActive      bool           `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProductVariant,
		arg.ID,
		arg.Name,
		arg.Sku,
		arg.Price,
		arg.StockQuantity,
		arg.IsActive,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Sku,
		&i.Price,
		&i.StockQuantity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariantStock = `-- name: UpdateVariantStock :exec
UPDATE product_variants SET stock_quantity = $2 WHERE id = $1
`

type UpdateVariantStockParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	StockQuantity int32       `db:"stock_quantity" json:"stock_quantity"`
}

func (q *Queries) UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) error {
	_, err := q.db.Exec(ctx, updateVariantStock, arg.ID, arg.StockQuantity)
	return err
}
