// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStoreSettings = `-- name: GetStoreSettings :one
SELECT id, tax_rate, shipping_cost, free_shipping_threshold, created_at, updated_at FROM store_settings WHERE id = 1
`

func (q *Queries) GetStoreSettings(ctx context.Context) (StoreSetting, error) {
	row := q.db.QueryRow(ctx, getStoreSettings)
	var i StoreSetting
	err := row.Scan(
		&i.ID,
		&i.TaxRate,
		&i.ShippingCost,
		&i.FreeShippingThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStoreSettings = `-- name: UpsertStoreSettings :one
INSERT INTO store_settings (id, tax_rate, shipping_cost, free_shipping_threshold)
VALUES (1, $1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET tax_rate = EXCLUDED.tax_rate,
    shipping_cost = EXCLUDED.shipping_cost,
    free_shipping_threshold = EXCLUDED.free_shipping_threshold
RETURNING id, tax_rate, shipping_cost, free_shipping_threshold, created_at, updated_at
`

type UpsertStoreSettingsParams struct {
	TaxRate               pgtype.Numeric `db:"tax_rate" json:"tax_rate"`
	ShippingCost          pgtype.Numeric `db:"shipping_cost" json:"shipping_cost"`
	FreeShippingThreshold pgtype.Numeric `db:"free_shipping_threshold" json:"free_shipping_threshold"`
}

func (q *Queries) UpsertStoreSettings(ctx context.Context, arg UpsertStoreSettingsParams) (StoreSetting, error) {
	row := q.db.QueryRow(ctx, upsertStoreSettings, arg.TaxRate, arg.ShippingCost, arg.FreeShippingThreshold)
	var i StoreSetting
	err := row.Scan(
		&i.ID,
		&i.TaxRate,
		&i.ShippingCost,
		&i.FreeShippingThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
